#!/usr/bin/env bash
# Fail if any source file exceeds the line cap.
# `database.types.ts` is generated by Supabase — exempt.
set -euo pipefail
LIMIT=600
OFFENDERS=$(find src supabase -type f \
  \( -name '*.ts' -o -name '*.tsx' -o -name '*.sql' \) \
  -not -path '*/node_modules/*' \
  -not -path '*/database.types.ts' \
  -exec wc -l {} + \
  | awk -v lim="$LIMIT" '$1 > lim && $2 != "total" { print $1, $2 }' \
  | sort -rn)
if [[ -n "$OFFENDERS" ]]; then
  echo "Files exceeding $LIMIT lines:"
  echo "$OFFENDERS"
  exit 1
fi
echo "All files within $LIMIT-line cap."
